name: Crypto Data Pipeline

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  scrape_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper
        run: python DefiLlamaScraper.py
        env:
          API_KEY: ${{ secrets.cmc_api_key }}

      - name: Upload Data to PostgreSQL
        run: python DefiLlama_to_postgres.py
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
