name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

env:
  CI: true
  MOCK_MODE: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run Flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        continue-on-error: true

      - name: Check formatting with Black
        run: black --check .
        continue-on-error: true

      - name: Check imports with isort
        run: isort --check --profile black .
        continue-on-error: true

  build-and-test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Install Docker Compose
        run: |
          # Install the latest version of Docker Compose
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          
          # Alternatively, install Docker Compose plugin
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          
          # Verify installation
          echo "Docker Compose version:"
          docker compose version || docker-compose version

      - name: Build Docker images
        run: docker-compose build

      - name: Start containers
        run: docker-compose up -d

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      
      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to start..."
          until docker-compose exec -T postgres pg_isready -U postgres; do
            echo "PostgreSQL is not ready yet, waiting..."
            sleep 2
          done
          echo "PostgreSQL is ready!"
        continue-on-error: true

      - name: Check pgvector extension
        run: |
          docker-compose exec -T postgres psql -U postgres -d crypto_data -c "SELECT extname FROM pg_extension WHERE extname = 'vector'"
        continue-on-error: true

      - name: Verify Python environment
        run: |
          echo "Python version:"
          docker-compose run --rm app python --version
          
          echo "Pip packages:"
          docker-compose run --rm app pip freeze

      - name: Test critical imports
        run: |
          echo "Testing critical imports..."
          docker-compose run --rm app python -c "import sys; print('Python path:', sys.path)"
          docker-compose run --rm app python -c "try: import psycopg2; print('psycopg2 imported successfully'); except ImportError as e: print(f'Error importing psycopg2: {e}')"
          docker-compose run --rm app python -c "try: import pgvector; print('pgvector imported successfully'); except ImportError as e: print(f'Error importing pgvector: {e}')"
          docker-compose run --rm app python -c "try: from data_lineage import DataLineage, LineageContext; print('Data lineage imported successfully'); except ImportError as e: print(f'Error importing data_lineage: {e}')"
          docker-compose run --rm app python -c "try: import langchain_rag; print('LangChain RAG imported successfully'); except ImportError as e: print(f'Error importing LangChain RAG: {e}')"
        continue-on-error: false
      
      - name: Run mock mode tests
        run: |
          echo "Testing DeFi Llama scraper in mock mode..."
          docker-compose run --rm app defi --mock
          
          echo "Testing Reddit scraper in mock mode..."
          docker-compose run --rm app reddit --mock
        continue-on-error: true
      
      - name: Test RAG implementations
        run: |  
          echo "Testing RAG system in mock mode..."
          docker-compose run --rm app rag --mock --query "Bitcoin"
        continue-on-error: true
          
      - name: Test LangChain components
        run: |
          echo "Testing LangChain RAG implementation in mock mode..."
          docker-compose run --rm app langchain-rag --mock --query "Bitcoin"
        continue-on-error: true
      
      - name: Test auxiliary scripts
        run: |
          echo "Testing example usage script in batch mode..."
          docker-compose run --rm app example --batch
          
          echo "Testing migration script in mock mode..."
          docker-compose run --rm app migrate --mock
          
          echo "Testing comparison of RAG implementations..."
          docker-compose run --rm app compare --query "Ethereum" --mock
        continue-on-error: true

      - name: Verify container logs
        run: docker-compose logs

      - name: Stop and remove containers
        if: always()  # Run this step even if previous steps fail
        run: docker-compose down -v 