name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run Flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        continue-on-error: true

      - name: Check formatting with Black
        run: black --check .
        continue-on-error: true

      - name: Check imports with isort
        run: isort --check --profile black .
        continue-on-error: true

  build-and-test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: docker-compose build

      - name: Start containers
        run: docker-compose up -d

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      
      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to start..."
          until docker-compose exec -T postgres pg_isready -U postgres; do
            echo "PostgreSQL is not ready yet, waiting..."
            sleep 2
          done
          echo "PostgreSQL is ready!"

      - name: Check pgvector extension
        run: |
          docker-compose exec -T postgres psql -U postgres -d crypto_data -c "SELECT extname FROM pg_extension WHERE extname = 'vector'"

      - name: Test imports
        run: |
          echo "Testing imports..."
          docker-compose run --rm app python -c "try: import langchain_rag; print('LangChain RAG imported successfully'); except ImportError as e: print(f'Error importing LangChain RAG: {e}')"
          docker-compose run --rm app python -c "try: from langchain_text_splitters import RecursiveCharacterTextSplitter; print('Text splitters imported successfully'); except ImportError as e: print(f'Error importing text splitters: {e}')"
          docker-compose run --rm app python -c "try: import compare_rag_implementations; print('Comparison script imported successfully'); except ImportError as e: print(f'Error importing comparison script: {e}')"
          docker-compose run --rm app python -c "try: import migrate_to_langchain; print('Migration script imported successfully'); except ImportError as e: print(f'Error importing migration script: {e}')"

      - name: Check module dependencies
        run: |
          docker-compose run --rm app pip freeze
      
      - name: Run pgvector tests
        run: docker-compose run --rm app test
        continue-on-error: true

      - name: Run mock mode tests
        run: |
          echo "Testing DeFi Llama scraper in mock mode..."
          docker-compose run --rm app defi --mock
          
          echo "Testing Reddit scraper in mock mode..."
          docker-compose run --rm app reddit --mock
          
          echo "Testing RAG system in mock mode..."
          docker-compose run --rm app rag --mock --query "Bitcoin"
        continue-on-error: false
          
      - name: Test LangChain components
        run: |
          echo "Testing LangChain RAG implementation in mock mode..."
          docker-compose run --rm app langchain-rag --mock --query "Bitcoin"
          
          echo "Testing example usage script in batch mode..."
          docker-compose run --rm app example --batch
          
          echo "Testing migration script in mock mode..."
          docker-compose run --rm app migrate --mock
          
          echo "Testing comparison of RAG implementations..."
          docker-compose run --rm app compare --query "Ethereum" --mock
        continue-on-error: true

      - name: Verify container logs
        run: docker-compose logs

      - name: Stop and remove containers
        if: always()  # Run this step even if previous steps fail
        run: docker-compose down -v 